# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
  - name: About us
    link: /introduction
  - name: Publications
    link: /publications
  - name: Datasets
    link: /datasets
  - name: Members
    submenu:
      - name: Mentor
        link: /members/mentor
      - name: Students
        link: /members/students
  - name: Schedules
    link: 
  - name: Reading Group
    link: https://github.com/multinlp-tju/TJU_MultiNLP_ReadingGroup
  - name: Tags
    link: /tags
  - name: Follow us
    submenu:
      - name: GitHub
        icon: github
        link: https://github.com/multinlp-tju
      - name: LinkedIn
        icon: linkedin-square
        link: https://github.com/multinlp-tju
      - name: Twitter
        icon: twitter
        link: https://github.com/multinlp-tju
    
