# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
  - name: Introduction
    link: /introduction
  - name: People
    submenu:
      - name: Mentor
        link: /projects/mentor
      - name: Students
        link: /projects/students
  - name: Poblications
    link: /publications
  - name: Datasets
    link: /datasets
  - name: Schedules
    link: https://github.com/multinlp-tju/TJU_MultiNLP_ReadingGroup
  - name: Tags
    link: /tag
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: https://github.com/multinlp-tju
      - name: LinkedIn
        icon: linkedin-square
        link: https://github.com/multinlp-tju
      - name: Twitter
        icon: twitter
        link: https://github.com/multinlp-tju
    
